---

- name: 'Ensures dir exists for pages on {{ module.key }}'
  file:
    path: '/opt/gluu-server-{{ gluu_version }}/opt/gluu/jetty/{{ gluu_modules_directory[module.key] }}/custom/pages/{{ item.dest | default(".") | dirname }}/'
    state: directory
  with_items:
    "{{ module.value }}"

- name: 'Copy pages for {{ module.key }}'
  template:
    src: '{{ item.path }}'
    dest: '/opt/gluu-server-{{ gluu_version }}/opt/gluu/jetty/{{ gluu_modules_directory[module.key] }}/custom/pages/{{ item.dest | default("./") }}'
  with_items:
    "{{ module.value }}"
    